### ISSUE TITLE
I get the following error when I try to run 'make' in the jni-build folder

### ISSUE THREAD

**Issue by NanditaDamaraju** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#10]
USER$ make
ndk-build
make[1]: Entering directory '/Users/nandita.damaraju/test/attempt13/Android-Face-Recognition-with-Deep-Learning-Library/jni-build' 
[arm64-v8a] Compile++      : jnilibsvm <= common.cpp
jni/common.cpp: In function 'void cmdToArgv(std::string, std::vector<char*>&)':
jni/common.cpp:28:40: error: 'malloc' was not declared in this scope
        char *c = (char*)malloc(c_size+1); // copy the null char in the end also
                                        ^
make[1]: *** [obj/local/arm64-v8a/objs/jnilibsvm/common.o] Error 1
make[1]: Leaving directory '/Users/nandita.damaraju/test/attempt13/Android-Face-Recognition-with-Deep-Learning-Library/jni-build'
make: *** [build] Error 2
USER$

**Comment by sladomic** [comment]
Maybe try first to only build the armeabi-v7a version instead of both (+ arm64-v8a). Seems to me, that your compiler source files for this architecture are missing.
