### ISSUE TITLE
Unable to optimise the custom model to detect faces

### ISSUE THREAD

**Issue by Zumbalamambo** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#11]
I have installed tensorflow in anaconda dir . I have trained and created a model now . I wish to optimize it.

I ran the following code

`bazel build tensorflow/tools/graph_transforms:transform_graph
`

But it is firing the following error,

> no such package 'tensorflow/tools/graph_transforms': BUILD file not found on package path.

**Comment by sladomic** [comment]
Tensorflow in anaconda is already built. What you need here is the TensorFlow source code. Then execute this command from the source code root folder. You should also see a BUILD file under "root folder/tensorflow/tools/graph_transforms".

**Comment by Zumbalamambo** [comment]
graph_transforms is not present inside anaconda folder. May I know where it is?

**Comment by sladomic** [comment]
Ah, I mean you need to download the TensorFlow source code from here https://github.com/tensorflow/tensorflow. There you will find it. In anaconda you can only find the already built Tensorflow binary.

**Comment by Zumbalamambo** [comment]
Sorry for the late reply. Thanks it worked
