### ISSUE TITLE
Training only last added person

### ISSUE THREAD

**Issue by Zumbalamambo** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#12]
Is it possible to train only the lastly added person instead of training from the scratch?

**Comment by sladomic** [comment]
I don't know any algorithm which allows a delta training, but probably you can find something online

**Comment by Zumbalamambo** [comment]
Can you give me a gist on how I can do so?

**Comment by sladomic** [comment]
What takes the most amount of time is usually the feature extraction. The easiest way to improve the speed of training would be to save the extracted features (were already done) so you don't need to extract them again (if you don't change the settings/parameters, however if you change some parameters then you should repeat the whole extraction again).

https://github.com/elimu-ai/authentication/blob/eabd87855f8fc541ea488b0a84a35c71f1147a1a/app/src/main/java/org/literacyapp/authentication/thread/TrainingThread.java#L103

Another solution would be incremental/online learning, but then you would need to find a library which implements it or you would need to code the whole algorithms yourself (e.g. incremental SVM).

**Comment by Zumbalamambo** [comment]
sorry for my late reply... is it possible to do that in python may be.. if so can you please share with me a gist on the same?

**Comment by Zumbalamambo** [comment]
@sladomic finally after months, I have managed to do it in the app... Thank you...

**Comment by rautsunil** [comment]
@Zumbalamambo  , Great to hear you made it working  ,but I am still facing the same problem to the confidence score on the Android App . I am using KNN. Could you please help me in to achieve  confidence score.

**Comment by sunnykinger** [comment]
@rautsunil are you able to achieve the confidence score?
