### ISSUE TITLE
source code of openCV jni lib

### ISSUE THREAD

**Issue by tomsang** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#23]
OpenCV detectMultiScale mode has memory leaking. The apk's memory gradually increases more than 1G in this mode, then crash will happen.

The memory leaking seems to happen in OpenCV jni lib.

Could we get the source codes of  OpenCV jni lib in order to find where the leaking is?

**Comment by sladomic** [comment]
Thanks for the investigation. We just use the original OpenCV Android package, which we uploaded to Bintray for easier access. So it has to be the original OpenCV source code.
