### ISSUE TITLE
detetctthe naame of a person

### ISSUE THREAD

**Issue by ashu-11** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#26]
If ii want to detect the name of a person in separate string after recognized by a this application how can i do this one ?

**Comment by ashu-11** [comment]
Because i want to use this name for some other purpose as well

**Comment by sladomic** [comment]
Hi @ashu-11 can you reformulate the question? I don't fully understand it.

**Comment by Zumbalamambo** [comment]
@ashu-11 just parse the string that you are getting from the classifier.
