### ISSUE TITLE
Need a "Getting Started Tutorial"

### ISSUE THREAD

**Issue by SapneshNaik** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#32]
Hi,

I am finding it very difficult to understand how to use this library. I get that the necessary steps are training and recognition.  Is there a simple example that shows how to do this? The library should be able to take a set of images for training (to add a person) and then an unknown image to try and recognize a known face in that picture.  Please help me.

Thanks,
Sapnesh

**Comment by Zumbalamambo** [comment]
@SapneshNaik  read the wiki and also the JavaDoc. It should be straight forward

**Comment by Zumbalamambo** [comment]
@Qualeams I think this issue can be closed
