### ISSUE TITLE
Error On Importing The Module

### ISSUE THREAD

**Issue by Ananda13th** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#33]
I tried to import the module, but get this error instead
`ERROR: Could not find method leftShift() for arguments [android_release_aar_8aaffqenud6qsg8w8hrovmfvc$_run_closure7@64a53476] on task ':facerecognitionlibrary:generateRelease' of type org.gradle.api.DefaultTask.`
Any advice for this? Thx

**Comment by yong2khoo-lm** [comment]
Oh My. I also hit this error. The post in stackoverflow doesn't it. I only manage to get rid of it by downgrading the gradle to 3.5.
Not sure you are doing the similar.
