### ISSUE TITLE
x86 supporting

### ISSUE THREAD

**Issue by thanoue** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#35]
how can i build the jni libs with x86 platform ?

**Comment by sladomic** [comment]
you'd need to add **x86** and/or **x86_64** in this file https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/blob/master/jni-build/jni/Application.mk before executing the make command https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#android-ndk---c

**Comment by sladomic** [comment]
I'm not 100% sure if the OpenCV x86 files are included though..if not, then you have to download and replace the OpenCV library as well as seen here https://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/android_dev_intro.html

**Comment by thanoue** [comment]
I fixed opencv issue, but when i use authentication, it crashed cause of
missing so file of your library

**Comment by sladomic** [comment]
first follow this https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/issues/35#issuecomment-680013392 and then this:

### Android NDK - C++
The libs for LIBSVM can be compiled outside of Android Studio with the make command (the Makefile is located under /jni-build). There are 3 different usages:

- make clean (executes ndk-build clean)
- make (executes ndk-build)
- make install (copies the libs to the folder /src/main/jniLibs/armeabi-v7a)

**Comment by thanoue** [comment]
> first follow this [#35 (comment)](https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/issues/35#issuecomment-680013392) and then this:
> 
> ### Android NDK - C++
> The libs for LIBSVM can be compiled outside of Android Studio with the make command (the Makefile is located under /jni-build). There are 3 different usages:
> 
> * make clean (executes ndk-build clean)
> * make (executes ndk-build)
> * make install (copies the libs to the folder /src/main/jniLibs/armeabi-v7a)

i build ndk-build by android studio, but it got error ERROR: executing external native build for ndkBuild, how can i fix it, thanks

**Comment by thanoue** [comment]
Thank you very much for the information. I have built successfully
