### ISSUE TITLE
Unable to create so file with the make file that has been provided

### ISSUE THREAD

**Issue by Zumbalamambo** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#7]
Im trying to convert tensorflow c++ files into so file

Following is the make file as in the project

```
build:
    ndk-build

install:
    cp -r libs/armeabi-v7a/*.so ../src/main/jniLibs/armeabi-v7a/
    cp -r libs/arm64-v8a/*.so ../src/main/jniLibs/arm64-v8a/

clean:
    ndk-build clean
```

 But it is not building so file.  What am I missing?

**Comment by sladomic** [comment]
What error do you get?

**Comment by Zumbalamambo** [comment]
rk-master/facerecognitionlibrary/jni-build/Makefile: line 1: build:: command not found
/Users/Zumbala/Documents/Android-Face-Recognition-with-Deep-Learning-Test-Framework-master/facerecognitionlibrary/jni-build/Makefile: line 2: ndk-build: command not found
/Users/Zumbala/Documents/Android-Face-Recognition-with-Deep-Learning-Test-Framework-master/facerecognitionlibrary/jni-build/Makefile: line 4: install:: command not found
cp: directory ../src/main/jniLibs/armeabi-v7a does not exist
cp: directory ../src/main/jniLibs/arm64-v8a does not exist
/Users/Zumbala/Documents/Android-Face-Recognition-with-Deep-Learning-Test-Framework-master/facerecognitionlibrary/jni-build/Makefile: line 8: clean:: command not found
/Users/Zumbala/Documents/Android-Face-Recognition-with-Deep-Learning-Test-Framework-master/facerecognitionlibrary/jni-build/Makefile: line 9: ndk-build: command not found
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by Zumbalamambo** [comment]
Thats the error that im getting

**Comment by sladomic** [comment]
You need to add the Android Ndk path to your PATH (if on Linux/OSX). I think the Makefile is only supported for Unix systems (so no Windows).

- So download the Android Ndk
- Then add the path to the Ndk to the PATH
- Then test in terminal/cmd if the ndk can be found by typing "ndk-build -h" and hit enter
- after you have setup the Ndk, go to the jni-build directory using terminal and enter "make" and hit enter

**Comment by Zumbalamambo** [comment]
Yes I have downloaded the NDK. I have set the path by executing the following command in my terminal. Im using Mac by the way. 


```
export ANDROID_SDK=/Users/Zumbala/Android/sdk
export ANDROID_NDK=/Users/Zumbala/Android/sdk/ndk-bundle
export PATH="$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$ANDROID_NDK"
```
but typing ndk-build -h fires the same error :(

**Comment by sladomic** [comment]
@Zumbalamambo for me it works:

export NDK_ROOT="~/Library/Android/sdk/ndk-bundle"
export PATH="$NDK_ROOT:$PATH"

macbook-pro:jni-build sladomic$ ndk-build -h
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
  --debug[=FLAGS]             Print various types of debugging information.
  -e, --environment-overrides

**Comment by sladomic** [comment]
@Zumbalamambo Did you try to execute "make" in the "jni-build" directory?

**Comment by Zumbalamambo** [comment]
Ok now i have tried executing in jni-build directory but it threw some error like, 

```
ndk-build
Android NDK: WARNING:jni/Android.mk:tensorflow: non-system libraries in linker flags: jni/libs/armeabi-v7a/libprotos_all_cc.a jni/libs/armeabi-v7a/libprotobuf.a jni/libs/armeabi-v7a/libprotobuf_lite.a /Users/Zumbala/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a /Users/Zumbala/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
Android NDK: WARNING:jni/Android.mk:tensorflow: non-system libraries in linker flags: jni/libs/arm64-v8a/libprotos_all_cc.a jni/libs/arm64-v8a/libprotobuf.a jni/libs/arm64-v8a/libprotobuf_lite.a /Users/Zumbala/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/libgnustl_static.a /Users/Zumbala/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/libsupc++.a    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
[armeabi-v7a] Install        : libjnilibsvm.so => libs/armeabi-v7a/libjnilibsvm.so
[armeabi-v7a] Compile++ arm  : tensorflow <= tensorflow_jni.cc
In file included from jni/tensorflow_jni.cc:31:0:
jni/genfiles/tensorflow/core/framework/step_stats.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
 #include <google/protobuf/stubs/common.h>
                                          ^
compilation terminated.
make[1]: *** [obj/local/armeabi-v7a/objs/tensorflow/tensorflow_jni.o] Error 1
make: *** [build] Error 2
```

I have tried installing brew  protobuf too

**Comment by sladomic** [comment]
Did you follow exactly these steps? https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/issues/1

It's important, that you use the right Protobuf version. Therefore download Tensorflow as follows:

git clone --recursive https://github.com/tensorflow/tensorflow.git

With --recursive you include the submodules (e.g. protobuf). Then after building, place all the files in the correct directory. And then execute make.

**Comment by Zumbalamambo** [comment]
I have downloaded it using `git clone --recursive https://github.com/tensorflow/tensorflow.git`.
I have placed it within jni-build filder and tried `make` . Im getting the same error :(

**Comment by Zumbalamambo** [comment]
When i tried to build with bazel, I got this error `Unexpected error reading .blazerc file '/Users/Zumbala/Documents/Android-Face-Recognition-with-Deep-Learning-Test-Framework-master/facerecognitionlibrary/jni-build/tensorflow/.tf_configure.bazelrc'`

**Comment by sladomic** [comment]
Try first if you can build the TensorFlow Android Demo in general:

Go to the Tensorflow folder and execute:
bazel build -c opt //tensorflow/examples/android:tensorflow_demo

**Comment by Zumbalamambo** [comment]
Okay now it works with make. Thank you

**Comment by sladomic** [comment]
I'm glad, that it works. For me it's the same. Everytime I upgrade to a new TensorFlow version, I first struggle with building even the simplest examples. This project has just too many dependencies :)
