### ISSUE TITLE
Is facerecognitionlibrary under the open source licenses?

### ISSUE THREAD

**Issue by aigeek** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#9]
Can I use the source code of facerecognitionlibrary. Then I can change the c/c++ codes  according to my needs. Tks!

**Comment by sladomic** [comment]
Yes, of course. Just bear in mind the license. But Apache 2.0 is open for reuse and code adaptations

**Comment by aigeek** [comment]
okey, thank you!
